# Generated by Django 5.1.4 on 2025-01-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.CharField(max_length=20)),
                ('billdate', models.DateField()),
                ('billstdname', models.CharField(max_length=50)),
                ('billconame', models.CharField(choices=[('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('UI/UX Design', 'UI/UX Design'), ('Data Analytics', 'Data Analytics')], default='', max_length=50)),
                ('billruppess', models.CharField(max_length=50)),
                ('billamount', models.CharField(max_length=50)),
                ('payment', models.CharField(default='Cash', max_length=50)),
            ],
            options={
                'db_table': 'bill_form',
            },
        ),
        migrations.CreateModel(
            name='Invoiceform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indate', models.DateField(error_messages='err')),
                ('sfname', models.CharField(max_length=50)),
                ('slname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('payment', models.CharField(default='Cash', max_length=50)),
                ('pcnumber', models.CharField(max_length=12, unique=True)),
                ('saddress', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('coname', models.CharField(choices=[('Python Full Stack', 'Python Full Stack'), ('Java Full Stack', 'Java Full Stack'), ('UI/UX Design', 'UI/UX Design'), ('Data Analytics', 'Data Analytics')], default='', max_length=50)),
                ('coduration', models.CharField(max_length=20)),
                ('cototal', models.CharField(max_length=20)),
                ('coins1', models.CharField(max_length=20)),
                ('coins2', models.CharField(max_length=20)),
                ('coins3', models.CharField(max_length=20)),
                ('coinsdate1', models.DateField()),
                ('coinsdate2', models.DateField()),
                ('coinsdate3', models.DateField()),
            ],
            options={
                'db_table': 'invoice_form',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('upassword', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
