# Generated by Django 5.1.4 on 2025-01-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0002_billform_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billform',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='myproject_app.invoiceform'),
        ),
    ]
