# Generated by Django 5.1.4 on 2025-01-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0003_alter_billform_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
