# Generated by Django 5.1.4 on 2025-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billform',
            name='billstdmobile',
            field=models.CharField(default='', max_length=20),
        ),
    ]
