# Generated by Django 5.1.4 on 2025-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0006_invoiceform_stdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceform',
            name='stdid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
