# Generated by Django 5.1.4 on 2025-01-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0007_alter_invoiceform_stdid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billform',
            name='billstdmobile',
            field=models.CharField(blank=True, default='!', max_length=20, null=True),
        ),
    ]
