# Generated by Django 5.1.4 on 2025-01-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0008_alter_billform_billstdmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billform',
            name='billstdmobile',
            field=models.CharField(blank=True, default=123, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='myproject_app.invoiceform')),
            ],
        ),
    ]
