# Generated by Django 5.1.4 on 2025-01-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0009_alter_billform_billstdmobile_installment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='installment',
            table='installment',
        ),
    ]
