# Generated by Django 5.1.4 on 2025-01-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0010_alter_installment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='installment',
            table=None,
        ),
    ]
