# Generated by Django 5.1.4 on 2025-01-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0011_alter_installment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
