# Generated by Django 5.1.4 on 2025-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0012_delete_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billform',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
